### ISSUE TITLE
support configuring comment style in Specification.toml

### ISSUE THREAD

**Issue by mimoo** [mimoo/cargo-specification#9]
First, I think we should have some good defaults when parsing files based on the file extension. Perhaps we can use this: https://docs.rs/comment-parser/latest/comment_parser/

Second, I think you should still be able to customize how the spec comment looks like:

```toml
[config]
custom_comments = [[".ml", "(*!", "*)"], [".py", "#!"]]
```
